version: "3.3"
services:
  ninjabot:
    restart: unless-stopped
    build: "./Docker/Volumes/Ninja"
    container_name: "ninjabot"
    depends_on:
      - mongodb
      - senither-weight
      - maro-api
      - redis
    volumes:
      - ./Docker/Volumes/Ninja:/application
  mongodb:
    image: mongo:3
    restart: unless-stopped
    #get rid of in prod
    environment:
      MONGO_INITDB_DATABASE: mongodb
      MONGO_INITDB_ROOT_USERNAME: VQUzCLSs60TpfFcT9AViaS0VlVDlBTpLXTRrRdkCRO6mXkCCcYHV1us2k3DksZXd
      MONGO_INITDB_ROOT_PASSWORD: fY2EL8sTwdVZRcvXssyb8jh85ut5hy6gbIcsYeDQxMUwd8O6x6loUumhxz3LKgqt
    volumes:
      - ./Docker/Volumes/mongodata:/data/db
  redis:
    image: redis:6.2.6
    restart: unless-stopped
    command: redis-server --requirepass "fY2EL8sTwdVZRcvXssyb8jh85ut5hy6gbIcsYeDQxMUwd8O6x6loUumhxz3LKgqt" --maxmemory 50mb --maxmemory-policy allkeys-lru
  senither-weight:
    build: "./Docker/Volumes/hypixel-skyblock-facade"
    container_name: senither-weight
    restart: unless-stopped
  maro-api:
    build: "./Docker/Volumes/maro-api"
    container_name: maro-api
    restart: unless-stopped
