version: "3.3"
services:
  ninjabot:
    restart: unless-stopped
    build: "./Docker/Volumes/Ninja"
    container_name: "ninjabot"
    depends_on:
      - mongodb
      - senither-weight
      - maro-api
    volumes:
      - ./Docker/Volumes/Ninja:/application
  mongodb:
    image: mongo:3
    restart: unless-stopped
    #get rid of in prod
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_DATABASE: mongodb
      MONGO_INITDB_ROOT_USERNAME: VQUzCLSs60TpfFcT9AViaS0VlVDlBTpLXTRrRdkCRO6mXkCCcYHV1us2k3DksZXd
      MONGO_INITDB_ROOT_PASSWORD: fY2EL8sTwdVZRcvXssyb8jh85ut5hy6gbIcsYeDQxMUwd8O6x6loUumhxz3LKgqt
    volumes:
      - ./Docker/Volumes/mongodata:/data/db
  senither-weight:
    image: senither/hypixel-skyblock-facade
    container_name: senither-weight
    restart: unless-stopped
  maro-api:
    build: './Docker/Volumes/maro-api'
    container_name: maro-api
    restart: unless-stopped
    #get rid of in prod
    ports:
      - "27018:3000"