name: Ninja-CheckTsc

on:
  push:
  pull_request:

jobs:
  tsc:
    name: tsc
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install node v16.6
      uses: actions/setup-node@v2
      with:
        node-version: 16.6
    - name: Install Yarn
      run: npm install --global yarn
    - name: Install Dependencies
      run: yarn install
    - name: Typescript Check
      run: yarn tsc -p Docker/Volumes/Ninja
